# Generated by Django 4.2.2 on 2023-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('pop', 'PopMusic'), ('jazz', 'JazzMusic'), ('r_b', 'R&BMusic'), ('rock', 'RockMusic'), ('country', 'Country Music'), ('dance', 'Dance Music'), ('hip_hop', 'Hip Hop Music'), ('other', 'Other')], max_length=30),
        ),
    ]
